In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]

In [3]:
a = torch.tensor(data)
b = torch.from_numpy(np.array(data))
print(a, b)

tensor([[1, 2],
        [3, 4]]) tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
c = torch.ones_like(b)
d = torch.rand_like(b, dtype = torch.float)  #, dtype = torch.float is important
print(c, d)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32) tensor([[0.4382, 0.1785],
        [0.5894, 0.7074]])


In [5]:
c_shape = c.shape
c_dtype = c.dtype
c_device = c.device
print(c_shape, c_dtype, c_device)

torch.Size([2, 2]) torch.int32 cpu


In [6]:
shape = (2, 3, 4)
e = torch.rand(shape)
f = torch.ones(shape)
g = torch.zeros(shape)
print(e, f, g)

tensor([[[0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604]],

        [[0.3222, 0.4790, 0.0099, 0.8116],
         [0.6835, 0.8644, 0.9121, 0.4993],
         [0.6066, 0.7815, 0.8592, 0.7533]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [7]:
if torch.cuda.is_available():
    e = e.to('cuda')
print(e)

tensor([[[0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604]],

        [[0.3222, 0.4790, 0.0099, 0.8116],
         [0.6835, 0.8644, 0.9121, 0.4993],
         [0.6066, 0.7815, 0.8592, 0.7533]]], device='cuda:0')


In [8]:
print(e[0])
print(e[1])
print(e[0].shape)
print(e[1].shape)
print('\n')

print(e[:, 0])
print(e[..., 0])
print(e[:, 1])
print(e[..., 1])
print('\n')

print(e[:, 0].shape)
print(e[..., 0].shape)
print(e[:, 1].shape)
print(e[..., 1].shape)

tensor([[0.7316, 0.7914, 0.4970, 0.5719],
        [0.6647, 0.4420, 0.8013, 0.5431],
        [0.5945, 0.2923, 0.9739, 0.1604]], device='cuda:0')
tensor([[0.3222, 0.4790, 0.0099, 0.8116],
        [0.6835, 0.8644, 0.9121, 0.4993],
        [0.6066, 0.7815, 0.8592, 0.7533]], device='cuda:0')
torch.Size([3, 4])
torch.Size([3, 4])


tensor([[0.7316, 0.7914, 0.4970, 0.5719],
        [0.3222, 0.4790, 0.0099, 0.8116]], device='cuda:0')
tensor([[0.7316, 0.6647, 0.5945],
        [0.3222, 0.6835, 0.6066]], device='cuda:0')
tensor([[0.6647, 0.4420, 0.8013, 0.5431],
        [0.6835, 0.8644, 0.9121, 0.4993]], device='cuda:0')
tensor([[0.7914, 0.4420, 0.2923],
        [0.4790, 0.8644, 0.7815]], device='cuda:0')


torch.Size([2, 4])
torch.Size([2, 3])
torch.Size([2, 4])
torch.Size([2, 3])


In [9]:
print(e[:, 0, 0])
print(e[..., 0, 0])
print(e[:, 1, 0])
print(e[..., 1, 0])
print('\n')

print(e[:, 0, 0].shape)
print(e[..., 0, 0].shape)
print(e[:, 1, 0].shape)
print(e[..., 1, 0].shape)

tensor([0.7316, 0.3222], device='cuda:0')
tensor([0.7316, 0.3222], device='cuda:0')
tensor([0.6647, 0.6835], device='cuda:0')
tensor([0.6647, 0.6835], device='cuda:0')


torch.Size([2])
torch.Size([2])
torch.Size([2])
torch.Size([2])


In [10]:
print(e[0, :])
print(e[0, ...])
print(e[1, :])
print(e[1, ...])
print('\n')

print(e[0, :].shape)
print(e[0, ...].shape)
print(e[1, :].shape)
print(e[1, ...].shape)
print('\n')

print(e[0, :, 0])
print(e[0, ..., 0])
print(e[1, :, 0])
print(e[1, ..., 0])
print('\n')

print(e[:, 0, 0].shape)
print(e[..., 0, 0].shape)
print(e[:, 1, 0].shape)
print(e[..., 1, 0].shape)

tensor([[0.7316, 0.7914, 0.4970, 0.5719],
        [0.6647, 0.4420, 0.8013, 0.5431],
        [0.5945, 0.2923, 0.9739, 0.1604]], device='cuda:0')
tensor([[0.7316, 0.7914, 0.4970, 0.5719],
        [0.6647, 0.4420, 0.8013, 0.5431],
        [0.5945, 0.2923, 0.9739, 0.1604]], device='cuda:0')
tensor([[0.3222, 0.4790, 0.0099, 0.8116],
        [0.6835, 0.8644, 0.9121, 0.4993],
        [0.6066, 0.7815, 0.8592, 0.7533]], device='cuda:0')
tensor([[0.3222, 0.4790, 0.0099, 0.8116],
        [0.6835, 0.8644, 0.9121, 0.4993],
        [0.6066, 0.7815, 0.8592, 0.7533]], device='cuda:0')


torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])


tensor([0.7316, 0.6647, 0.5945], device='cuda:0')
tensor([0.7316, 0.6647, 0.5945], device='cuda:0')
tensor([0.3222, 0.6835, 0.6066], device='cuda:0')
tensor([0.3222, 0.6835, 0.6066], device='cuda:0')


torch.Size([2])
torch.Size([2])
torch.Size([2])
torch.Size([2])


In [12]:
h = torch.cat([e, e], dim = 0)
print(h, h.shape, sep = "\n")
h = torch.cat([e, e], dim = 1)
print(h, h.shape, sep = "\n")
h = torch.cat([e, e], dim = 2)
print(h, h.shape, sep = "\n")
h = torch.cat([e, e], dim = 3)
print(h, h.shape, sep = "\n")

tensor([[[0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604]],

        [[0.3222, 0.4790, 0.0099, 0.8116],
         [0.6835, 0.8644, 0.9121, 0.4993],
         [0.6066, 0.7815, 0.8592, 0.7533]],

        [[0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604]],

        [[0.3222, 0.4790, 0.0099, 0.8116],
         [0.6835, 0.8644, 0.9121, 0.4993],
         [0.6066, 0.7815, 0.8592, 0.7533]]], device='cuda:0')
torch.Size([4, 3, 4])
tensor([[[0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604],
         [0.7316, 0.7914, 0.4970, 0.5719],
         [0.6647, 0.4420, 0.8013, 0.5431],
         [0.5945, 0.2923, 0.9739, 0.1604]],

        [[0.3222, 0.4790, 0.0099, 0.8116],
         [0.6835, 0.8644, 0.9121, 0.4993],
         [0.6066, 0.7815, 0.8592, 0.7533],
         [0.3222, 0.4790, 0.0099, 0.8116],
     

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [13]:
print(e.T.shape)
i = f @ torch.rand(2, 4, 3)
print(i.shape, sep = '\n')
i = f @ torch.rand(2, 4, 15)
print(i.shape, sep = '\n')

torch.Size([4, 3, 2])
torch.Size([2, 3, 3])
torch.Size([2, 3, 15])


In [14]:
j = torch.rand(2, 3, 4, 5) @ torch.rand(2, 3, 5, 5)
print(j.shape, sep = '\n')
j = torch.rand(2, 3, 4, 5) @ torch.rand(2, 3, 5, 52)
print(j.shape, sep = '\n')
j = torch.rand(2, 3, 4, 5) @ torch.rand(2, 4, 5, 5)
print(j.shape, sep = '\n')

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 52])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [15]:
j1 = torch.rand(2, 3, 4, 5)
j2 = torch.rand(2, 3, 5, 5)
j = j1.matmul(j2)
print(j.shape, sep = '\n')

j1 = torch.rand(2, 3, 4, 5)
j2 = torch.rand(2, 3, 5, 52)
j = j1.matmul(j2)
print(j.shape, sep = '\n')

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 52])


In [16]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())
#torch.Size([])

# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
print(torch.matmul(tensor1, tensor2).size())
#torch.Size([3])

# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
print(torch.matmul(tensor1, tensor2).size())
#torch.Size([10, 3])

# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
print(torch.matmul(tensor1, tensor2).size())
#torch.Size([10, 3, 5])

# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
print(torch.matmul(tensor1, tensor2).size())
#torch.Size([10, 3, 5])

tensor(2.3292)
torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [17]:
j1 = torch.rand(2, 3)
j2 = torch.rand(2, 3)
j = j1.mul(j2)
print(j, j.shape, sep = '\n')
j = j1 * j2
print(j, j.shape, sep = '\n')
j = j1 + j2
print(j, j.shape, sep = '\n')
j = j1 - j2
print(j, j.shape, sep = '\n')
j = j1 / j2
print(j, j.shape, sep = '\n')
j = j1 // j2
print(j, j.shape, sep = '\n')
j1 = torch.rand(2, 3)
j2 = torch.rand(2, 4)
print(j, j.shape, sep = '\n')
j = j1 * j2

tensor([[0.0883, 0.0027, 0.2335],
        [0.0055, 0.2372, 0.2411]])
torch.Size([2, 3])
tensor([[0.0883, 0.0027, 0.2335],
        [0.0055, 0.2372, 0.2411]])
torch.Size([2, 3])
tensor([[0.6077, 0.1134, 1.0892],
        [0.1503, 1.1928, 0.9967]])
torch.Size([2, 3])
tensor([[-0.1272, -0.0469, -0.5024],
        [ 0.0215, -0.6884,  0.1698]])
torch.Size([2, 3])
tensor([[0.6538, 0.4150, 0.3687],
        [1.3347, 0.2681, 1.4108]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [1., 0., 1.]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [1., 0., 1.]])
torch.Size([2, 3])


C:\Users\Keyha\.virtualenvs\things-to-read-again-E7o4ITPW\lib\site-packages\torch\_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [18]:
a = f.sum()
print(a, type(a))
a = a.item()
print(a, type(a))
a = f.item()
print(a, type(a))

tensor(24.) <class 'torch.Tensor'>
24.0 <class 'float'>


ValueError: only one element tensors can be converted to Python scalars

In [19]:
print(f)
print('\n')
print(f + 5)
print('\n')
print(f.add(5))
print('\n')
print(f)
print('\n')
print(f.add_(5))
print(f)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]])


tensor([[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]])
tensor([[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]

In [23]:
t = f.numpy()
print(t, type(t))
print(f)
f.add_(-5)
print(t, f)

[[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]] <class 'numpy.ndarray'>
tensor([[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]])
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
