## Testing simple math and numpy operations: Part 1

In [1]:
import math
import numpy as np

np.set_printoptions(precision = 3)

In [2]:
print(abs(-2))
print(abs(-2.1))
print(abs(-2.1 + 1.5j))

2
2.1
2.5806975801127883


In [3]:
a = -2.1 + 1.5j
print(a.real)
print(a.imag)

-2.1
1.5


In [4]:
print(pow(2, 2))
print(pow(a, 2))
print(pow(a, -1))
print(pow(a, 0))

4
(2.16-6.300000000000001j)
(-0.3153153153153153-0.2252252252252252j)
(1+0j)


In [6]:
print(round(3.1415, 2))
print(round(a, 1))
# round for complex number fails

3.14


TypeError: type complex doesn't define __round__ method

In [7]:
b = [4, 5, 3, 5, 3, 1, -1, 6]
c = [a, a * 2, -1, 2, 4, 5]

In [8]:
print(sorted(b))
print(sorted(b, reverse = True))
print(sorted(c))
print(sorted(c, reverse = True))
# sorted for complex number fails

[-1, 1, 3, 3, 4, 5, 5, 6]
[6, 5, 5, 4, 3, 3, 1, -1]


TypeError: '<' not supported between instances of 'complex' and 'complex'

In [9]:
d = [(4, 1), (4, 5), (2, 3), (8, 5), (1, 3), (5, 1), (4, -1), (42, 6)]
print(sorted(d))
print(sorted(d, reverse = True))
print(sorted(d, key = lambda item: item[1]))

[(1, 3), (2, 3), (4, -1), (4, 1), (4, 5), (5, 1), (8, 5), (42, 6)]
[(42, 6), (8, 5), (5, 1), (4, 5), (4, 1), (4, -1), (2, 3), (1, 3)]
[(4, -1), (4, 1), (5, 1), (2, 3), (1, 3), (4, 5), (8, 5), (42, 6)]


In [10]:
e = [{4, 1}, {4, 5}, {2, 3}, {8, 5}, {1, 3}, {5, 1}, {4, -1}, {42, 6}]
print(sorted(e))
print(sorted(e, reverse = True))
print(sorted(e, key = lambda item: item[1]))  # fails

[{1, 4}, {4, 5}, {2, 3}, {8, 5}, {1, 3}, {1, 5}, {4, -1}, {42, 6}]
[{1, 4}, {4, 5}, {2, 3}, {8, 5}, {1, 3}, {1, 5}, {4, -1}, {42, 6}]


TypeError: 'set' object is not subscriptable

In [11]:
f = {4: 2, 6: 4, -1: 9, 41: -3}
print(f.items())
print(f.keys())
print(f.values())
print(sorted(f))
print(dict(sorted(f.items(), key = lambda item: item[0])))
print(dict(sorted(f.items(), key = lambda item: item[1])))

dict_items([(4, 2), (6, 4), (-1, 9), (41, -3)])
dict_keys([4, 6, -1, 41])
dict_values([2, 4, 9, -3])
[-1, 4, 6, 41]
{-1: 9, 4: 2, 6: 4, 41: -3}
{41: -3, 4: 2, 6: 4, -1: 9}


In [12]:
g = [{4: 1}, {4: 5}, {2: 3}, {8: 5}, {1: 3}, {5: 1}, {4: -1}, {42: 6}]
try:
    print(sorted(g))  # fails
except Exception as ex:
    print(ex)

print(sorted(g, key = lambda item: list(item.keys())[0]))
print(sorted(g, key = lambda item: list(item.values())[0]))

'<' not supported between instances of 'dict' and 'dict'
[{1: 3}, {2: 3}, {4: 1}, {4: 5}, {4: -1}, {5: 1}, {8: 5}, {42: 6}]
[{4: -1}, {4: 1}, {5: 1}, {2: 3}, {1: 3}, {4: 5}, {8: 5}, {42: 6}]


In [13]:
print(min(b))
print(max(b))
print(min(d))
print(max(d))
print(min(e))
print(max(e))
print(min(f))
print(max(f))
try:
    print(min(g))  #fails
except Exception as ex:
    print(ex)

try:
    print(min(c))  # fails
except Exception as ex:
    print(ex)

-1
6
(1, 3)
(42, 6)
{1, 4}
{1, 4}
-1
41
'<' not supported between instances of 'dict' and 'dict'
'<' not supported between instances of 'complex' and 'complex'


In [14]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


In [15]:
print(2 ** 3)
print(math.sqrt(9))
print(a ** 0.5)
print(math.sqrt(a))

8
3.0
(0.4902538016745959+1.5298198554262505j)


TypeError: can't convert complex to float

In [16]:
print(math.log(math.e))
print(math.log(12, 10))
print(math.log(a, 3))

1.0
1.0791812460476247


TypeError: can't convert complex to float

In [17]:
deg = 182
rad = math.pi / 2 * 0.99
print(math.degrees(rad))
print(math.radians(deg))
print(math.cos(rad))
print(math.sin(rad))
print(math.tan(rad))

89.10000000000001
3.1764992386296798
0.015707317311820648
0.9998766324816606
63.6567411628717


In [18]:
num = 1.23e-8
num * 2

2.46e-08

In [19]:
np_b = np.array(b)
np_c = np.array(c)
print(np_b)
print(np_c)

[ 4  5  3  5  3  1 -1  6]
[-2.1+1.5j -4.2+3.j  -1. +0.j   2. +0.j   4. +0.j   5. +0.j ]


In [20]:
print(np_b + 1)
print(np_c + 1)

print(2 ** (np_b + 1))
print(2 ** (np_c + 1))

[5 6 4 6 4 2 0 7]
[-1.1+1.5j -3.2+3.j   0. +0.j   3. +0.j   5. +0.j   6. +0.j ]
[ 32  64  16  64  16   4   1 128]
[ 2.363e-01+0.402j -5.299e-02+0.095j  1.000e+00+0.j     8.000e+00+0.j
  3.200e+01+0.j     6.400e+01+0.j   ]


In [21]:
print(len(np_b))
np_d = np.ones(8)
print(np_d)

8
[1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
print(np_b - np_d)
print(np_b * np_d)
print(True) if np.array_equal(np_b * np_d, np_b) else print(False)
print(True) if np.allclose(np_b * np_d, np_b) else print(False)
print(np_c - np_d)

[ 3.  4.  2.  4.  2.  0. -2.  5.]
[ 4.  5.  3.  5.  3.  1. -1.  6.]
True
True


ValueError: operands could not be broadcast together with shapes (6,) (8,) 

In [23]:
np_e = np.arange(8)
print(np_e)

[0 1 2 3 4 5 6 7]


In [24]:
np_f = np.ones((3, 4, 5))
print(np_f)
print(len(np_f))
print(np_f.shape)
np_g = np.arange((3, 3, 4))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
3
(3, 4, 5)


TypeError: arange: scalar arguments expected instead of a tuple.

In [25]:
#elementwise
np_g = np.ones((3, 4, 5)) + 3
print(np_g)
print(np_f * np_g)
print(np_f * np_g * np_g)
print(np_f * np_g / np_g)
print(np_f * np_g % np_g)

[[[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]
[[[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]
[[[16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]]

 [[16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]]

 [[16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]
  [16. 16. 16. 16. 16.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0

In [26]:
print(np.sin(np_f))
print(np.sin(np_f))

[[[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]

 [[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]

 [[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]]
[[[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]

 [[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]

 [[0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]
  [0.841 0.841 0.841 0.841 0.841]]]


In [27]:
t = np.array(np_g == np_f)
print(t)
t = np.array(np_g > np_f)
print(t)
t = np.array(np_g > 4)
print(t)

[[[False False False False False]
  [False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]
  [False False False False False]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
[[[False False False False False]
  [False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
