## Testing simple math and numpy operations: Part 2


In [1]:
import math
import numpy as np

np.set_printoptions(precision = 3)

In [13]:
a = np.triu(np.ones((3, 4)), 1)
print(a)
print(a.T)

a = np.triu(np.ones((4, 4)), 0)
print(a)
print(a.T)

[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [32]:
b = np.arange(15).reshape(3, 5)
print(b)

b_rand=np.random.rand(2,3,4)
print(b_rand,b_rand.shape)

b = np.arange(15).reshape(3, 6)
print(b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[0.108 0.278 0.992 0.316]
  [0.849 0.065 0.107 0.915]
  [0.04  0.125 0.388 0.545]]

 [[0.379 0.188 0.148 0.823]
  [0.775 0.649 0.041 0.305]
  [0.222 0.61  0.795 0.78 ]]] (2, 3, 4)


ValueError: cannot reshape array of size 15 into shape (3,6)

In [16]:
c = np.sum(b)
print(c)
b.sum()

105


105

In [27]:
print(b.shape)
print(b.sum(axis = 0))
print(b.sum(axis = 1))
print(b[:,0].sum())

c = np.arange(72).reshape(3, 6, 4)
print(c.shape)
print(c.sum(axis = 0))
print(c.sum(axis = 0).shape)
print(c.sum(axis = 1))
print(c.sum(axis = 1).shape)
print(c.sum(axis = 2))
print(c.sum(axis = 2).shape)


(3, 5)
[15 18 21 24 27]
[10 35 60]
15
(3, 6, 4)
[[ 72  75  78  81]
 [ 84  87  90  93]
 [ 96  99 102 105]
 [108 111 114 117]
 [120 123 126 129]
 [132 135 138 141]]
(6, 4)
[[ 60  66  72  78]
 [204 210 216 222]
 [348 354 360 366]]
(3, 4)
[[  6  22  38  54  70  86]
 [102 118 134 150 166 182]
 [198 214 230 246 262 278]]
(3, 6)


In [6]:

np_h = np.array([1, 2, 3])
np_i = np.array([1, 2, 3, 4])
# out(M, N) ndarray, Input is flattened if not already 1-dimensional.
# out[i, j] = a[i] * b[j]
print(np.outer(np_h, np_i))
print(np.outer(np_i, np_h))
print(np.outer(np.ones((2, 2)), np_h))
print(np.outer(np.ones((2, 2)), np_h).shape)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(4, 3)


[source](https://stackoverflow.com/questions/11033573/difference-between-numpy-dot-and-inner)

np.inner is sometimes called a "vector product" between a higher and lower order
tensor, particularly a tensor times a vector, and often leads to "tensor contraction".
It includes matrix-vector multiplication.

np.dot corresponds to a "tensor product", and includes the case mentioned at the
bottom of the Wikipedia page. It is generally used for multiplication of two
similar tensors to produce a new tensor. It includes matrix-matrix multiplication.

In [7]:
print(np.inner(np_f, np_g))
print(np.dot(np_f, np_g))


NameError: name 'np_f' is not defined