## What are Eigenvalues and Eigenvectors?


In [1]:
import scipy.linalg as la
import numpy as np

np.set_printoptions(precision = 3)

## Definition

[Source](https://github.com/patrickwalls/mathematical-python/)

Let $A$ be a square matrix. A non-zero vector $\mathbf{v}$ is an [eigenvector](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) for $A$ with [eigenvalue](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) $\lambda$ if

$$
A\mathbf{v} = \lambda \mathbf{v}
$$

Rearranging the equation, we see that $\mathbf{v}$ is a solution of the homogeneous system of equations

$$
\left( A - \lambda I \right) \mathbf{v} = \mathbf{0}
$$

where $I$ is the identity matrix of size $n$. Non-trivial solutions exist only if the matrix $A - \lambda I$ is singular which means $\mathrm{det}(A - \lambda I) = 0$. Therefore eigenvalues of $A$ are roots of the [characteristic polynomial](https://en.wikipedia.org/wiki/Characteristic_polynomial)

$$
p(\lambda) = \mathrm{det}(A - \lambda I)
$$

## Examples

In [2]:
A = np.array([[1, 0], [0, -2]])
print(A)

[[ 1  0]
 [ 0 -2]]


In [3]:
results = la.eig(A)
print(results)

(array([ 1.+0.j, -2.+0.j]), array([[1., 0.],
       [0., 1.]]))


results is a tuple with (eigvals,eigvecs). eigvals is 1D numpy array. eigvecs is 2D
numpy array.

[Source](https://math.stackexchange.com/questions/67304/do-real-matrices-always-have-real-eigenvalues)

Do real matrices always have real eigenvalues?
Real symmetric matrices do, but otherwise not necessarily.

If a matrix with real entries is symmetric (equal to its own transpose)
then its eigenvalues are real (and its eigenvectors are orthogonal). Every n×n matrix whose entries are real has at least one real eigenvalue
if n is odd. That is because the characteristic polynomial has real coefficients
so the complex conjugate of a root is another root, and you can't have an odd number
of roots if they come in pairs of distinct entries.

In [4]:
print("Check whether A is equal to its own transpose")
print(True) if np.array_equal(A.T, A) else print(False)

print("Check whether B is equal to its own transpose")
B = np.array([[1, 1, 3], [4, -2, 5], [2, -4, 5]])
print(True) if np.array_equal(B.T, B) else print(False)
print(B)
results = la.eig(B)
print(results)

Check whether A is equal to its own transpose
True
Check whether B is equal to its own transpose
False
[[ 1  1  3]
 [ 4 -2  5]
 [ 2 -4  5]]
(array([-2.183+0.j   ,  3.091+2.634j,  3.091-2.634j]), array([[-0.651+0.j   ,  0.553-0.089j,  0.553+0.089j],
       [ 0.572+0.j   ,  0.67 +0.j   ,  0.67 -0.j   ],
       [ 0.5  +0.j   ,  0.24 +0.424j,  0.24 -0.424j]]))


In [6]:
# eigenvalues
print(results[0].real)
print(results[0].imag)

[-2.183  3.091  3.091]
[ 0.     2.634 -2.634]


In [7]:
#eigenvectors
print(results[1])

[[-0.651+0.j     0.553-0.089j  0.553+0.089j]
 [ 0.572+0.j     0.67 +0.j     0.67 -0.j   ]
 [ 0.5  +0.j     0.24 +0.424j  0.24 -0.424j]]


In [19]:
print(results[1][:, 1])
v1 = results[1][:, 1].reshape(3, 1)
print(v1)

[0.553-0.089j 0.67 +0.j    0.24 +0.424j]
[[0.553-0.089j]
 [0.67 +0.j   ]
 [0.24 +0.424j]]


In [13]:
B @ v1

array([[ 1.943+1.183j],
       [ 2.072+1.765j],
       [-0.375+1.942j]])

In [10]:
results[0][1] * v1

array([[ 1.943+1.183j],
       [ 2.072+1.765j],
       [-0.375+1.942j]])

In [18]:
# let's check for other eigenvectors and values
for n in range(3):
    d = 3
    v = results[1][:, n].reshape(d, 1)
    print(v)
    print(True) if np.allclose(B @ v, results[0][n] * v) else print(False)

[[-0.651+0.j]
 [ 0.572+0.j]
 [ 0.5  +0.j]]
True
[[0.553-0.089j]
 [0.67 +0.j   ]
 [0.24 +0.424j]]
True
[[0.553+0.089j]
 [0.67 -0.j   ]
 [0.24 -0.424j]]
True
